# Generated by Django 5.2.6 on 2025-10-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Platform name (e.g., 'Main Doctor Platform')", max_length=200, unique=True)),
                ('api_url', models.URLField(help_text='API endpoint URL')),
                ('api_key', models.CharField(blank=True, help_text='API authentication key', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='API secret/token', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Platform Config',
                'verbose_name_plural': 'Doctor Platform Configs',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='platform_appointment_id',
            field=models.CharField(blank=True, help_text='ID from doctor platform', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='platform_sync_date',
            field=models.DateTimeField(blank=True, help_text='Last sync date', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sync_error_message',
            field=models.TextField(blank=True, help_text='Last sync error message'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='synced_to_platform',
            field=models.BooleanField(default=False, help_text='Whether synced to doctor platform'),
        ),
    ]
