# Generated by Django 5.2.6 on 2025-10-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctorplatformconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('checkup', 'Check Up'), ('cleaning', 'Cleaning'), ('filling', 'Filling'), ('custom', 'Custom')], max_length=50),
        ),
    ]
