# Generated by Django 5.2.6 on 2025-10-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, help_text='Assigned doctor', max_length=200, null=True),
        ),
    ]
