# Generated by Django 5.2.6 on 2025-10-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Google Calendar', help_text='Configuration name', max_length=200)),
                ('calendar_id', models.EmailField(help_text='Google Calendar ID (usually your email)', max_length=254)),
                ('credentials_json', models.TextField(help_text='Google API credentials JSON content')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable Google Calendar sync')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Calendar Config',
                'verbose_name_plural': 'Google Calendar Configs',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_error_message',
            field=models.TextField(blank=True, help_text='Last Google Calendar sync error'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID', max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_calendar_sync_date',
            field=models.DateTimeField(blank=True, help_text='Last Google Calendar sync date', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='synced_to_google_calendar',
            field=models.BooleanField(default=False, help_text='Whether synced to Google Calendar'),
        ),
    ]
