# Generated by Django 5.2.6 on 2025-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_googlecalendarconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarconfig',
            name='auth_type',
            field=models.CharField(choices=[('oauth', 'OAuth 2.0 (Recommended)'), ('service_account', 'Service Account')], default='oauth', help_text='Authentication type', max_length=20),
        ),
        migrations.AddField(
            model_name='googlecalendarconfig',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='OAuth authorization status'),
        ),
        migrations.AddField(
            model_name='googlecalendarconfig',
            name='token_json',
            field=models.TextField(blank=True, help_text='OAuth token (auto-generated after authorization)'),
        ),
        migrations.AlterField(
            model_name='googlecalendarconfig',
            name='credentials_json',
            field=models.TextField(help_text='Google API credentials JSON content (OAuth client secret or Service Account key)'),
        ),
    ]
